# Generated by Django 3.2.14 on 2022-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_dni',
            field=models.CharField(default='dni', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
