# Generated by Django 3.2.14 on 2022-11-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0002_auto_20221101_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='tipo_dni',
        ),
    ]
